# Cleaning Data Notebook for World Data Bank csv

### JJ

In [115]:
import pandas as pd
import numpy as np
import math
import base64

In [116]:
#Notes will be for me to kind of write down what i'm doing to remind/teach myslef
#Importing Data
df = pd.read_csv('/Users/josejimenez/Downloads/WDI_csv/WDIData.csv')

#I have to find the path in my files and use that

In [117]:
df.head(10)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
0,Arab World,ARB,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.702495,74.944860,76.258066,77.120464,78.094440,79.062000,79.851681,80.570536,81.210886,81.809630,82.368101,82.783289,83.120303,83.533457,83.897596,84.171599,84.510171,NaN,NaN,NaN,NaN,NaN
1,Arab World,ARB,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.297851,78.302779,78.980861,78.479364,80.023047,77.999111,79.306311,79.537184,80.574728,84.621206,82.926878,83.644992,84.270921,86.959991,87.199474,87.512260,88.129881,87.275323,88.720097,89.308602,90.283638,89.286856,NaN,NaN,NaN
2,Arab World,ARB,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.173305,56.103435,57.350189,57.353298,59.528339,60.383730,62.112010,63.261702,61.626342,64.908930,66.246450,64.850152,64.471295,66.612006,72.367301,68.805997,72.135831,70.506461,75.816160,75.958878,77.251714,78.165706,75.512153,78.211000,79.065508,81.102134,79.248100,NaN,NaN,NaN
3,Arab World,ARB,"Access to electricity, urban (% of urban popul...",EG.ELC.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.574429,93.022834,93.321986,93.601289,93.556321,95.141707,94.939743,95.712972,95.065438,96.290866,96.466418,96.435957,96.772853,96.466705,96.936319,97.290083,97.467915,97.063959,NaN,NaN,NaN
4,Arab World,ARB,Account ownership at a financial institution o...,FX.OWN.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.260538,NaN,NaN,30.277130,NaN,NaN,37.165211,NaN,NaN,NaN,NaN
5,Arab World,ARB,Account ownership at a financial institution o...,FX.OWN.TOTL.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.775815,NaN,NaN,22.079350,NaN,NaN,25.635403,NaN,NaN,NaN,NaN
6,Arab World,ARB,Account ownership at a financial institution o...,FX.OWN.TOTL.MA.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.377668,NaN,NaN,37.790764,NaN,NaN,48.328518,NaN,NaN,NaN,NaN
7,Arab World,ARB,Account ownership at a financial institution o...,FX.OWN.TOTL.OL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.741285,NaN,NaN,34.216583,NaN,NaN,42.542046,NaN,NaN,NaN,NaN
8,Arab World,ARB,Account ownership at a financial institution o...,FX.OWN.TOTL.40.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.067781,NaN,NaN,22.779890,NaN,NaN,27.724781,NaN,NaN,NaN,NaN
9,Arab World,ARB,Account ownership at a financial institution o...,FX.OWN.TOTL.PL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.051660,NaN,NaN,21.278042,NaN,NaN,26.458111,NaN,NaN,NaN,NaN

In [118]:
df.columns

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', 'Unnamed: 65'],
      dtype='object')

In [119]:
df.dtypes

Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960              float64
                   ...
2017              float64
2018              float64
2019              float64
2020              float64
Unnamed: 65       float64
Length: 66, dtype: object

I feel like `Country Name` and `Country Code` and `Indicator Name` -but i worry about that column being so fucking long -should both be categories

In [120]:
df['Country Name'] = df['Country Name'].astype('category')
df['Country Code'] = df['Country Code'].astype('category')

In [121]:
df.dtypes

Country Name      category
Country Code      category
Indicator Name      object
Indicator Code      object
1960               float64
                    ...
2017               float64
2018               float64
2019               float64
2020               float64
Unnamed: 65        float64
Length: 66, dtype: object

Because `Indicator Code` will not be consistent with other data sets i think we should DELETE the shit out of them

In [122]:
df.drop(columns = ['Indicator Code'], inplace = True)

In [123]:
df.rename({'Country Name': 'country_id', 'Country Code': 'ID', "Indicator Name": "indicator_name" }, axis=1, inplace = True)

In [124]:
df.head(25) # I keep not thinking about the inplace this was just to check

,country_id,ID,indicator_name,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
0,Arab World,ARB,Access to clean fuels and technologies for coo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.370250e+01,7.494486e+01,7.625807e+01,7.712046e+01,7.809444e+01,7.906200e+01,7.985168e+01,8.057054e+01,8.121089e+01,8.180963e+01,8.236810e+01,8.278329e+01,8.312030e+01,8.353346e+01,8.389760e+01,8.417160e+01,8.451017e+01,NaN,NaN,NaN,NaN,NaN
1,Arab World,ARB,Access to electricity (% of population),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.729785e+01,7.830278e+01,7.898086e+01,7.847936e+01,8.002305e+01,7.799911e+01,7.930631e+01,7.953718e+01,8.057473e+01,8.462121e+01,8.292688e+01,8.364499e+01,8.427092e+01,8.695999e+01,8.719947e+01,8.751226e+01,8.812988e+01,8.727532e+01,8.872010e+01,8.930860e+01,9.028364e+01,8.928686e+01,NaN,NaN,NaN
2,Arab World,ARB,"Access to electricity, rural (% of rural popul...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.417330e+01,5.610343e+01,5.735019e+01,5.735330e+01,5.952834e+01,6.038373e+01,6.211201e+01,6.326170e+01,6.162634e+01,6.490893e+01,6.624645e+01,6.485015e+01,6.447130e+01,6.661201e+01,7.236730e+01,6.880600e+01,7.213583e+01,7.050646e+01,7.581616e+01,7.595888e+01,7.725171e+01,7.816571e+01,7.551215e+01,7.821100e+01,7.906551e+01,8.110213e+01,7.924810e+01,NaN,NaN,NaN
3,Arab World,ARB,"Access to electricity, urban (% of urban popul...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.457443e+01,9.302283e+01,9.332199e+01,9.360129e+01,9.355632e+01,9.514171e+01,9.493974e+01,9.571297e+01,9.506544e+01,9.629087e+01,9.646642e+01,9.643596e+01,9.677285e+01,9.646671e+01,9.693632e+01,9.729008e+01,9.746791e+01,9.706396e+01,NaN,NaN,NaN
4,Arab World,ARB,Account ownership at a financial institution o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.226054e+01,NaN,NaN,3.027713e+01,NaN,NaN,3.716521e+01,NaN,NaN,NaN,NaN
5,Arab World,ARB,Account ownership at a financial institution o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.377582e+01,NaN,NaN,2.207935e+01,NaN,NaN,2.563540e+01,NaN,NaN,NaN,NaN
6,Arab World,ARB,Account ownership at a financial institution o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.037767e+01,NaN,NaN,3.779076e+01,NaN,NaN,4.832852e+01,NaN,NaN,NaN,NaN
7,Arab World,ARB,Account ownership at a financial institution o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.574129e+01,NaN,NaN,3.421658e+01,NaN,NaN,4.254205e+01,NaN,NaN,NaN,NaN
8,Arab World,ARB,Account ownership at a financial institution o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.606778e+01,NaN,NaN,2.277989e+01,NaN,NaN,2.772478e+01,NaN,NaN,NaN,NaN
9,Arab World,ARB,Account ownership at a financial institution o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.405166e+01,NaN,NaN,2.127804e+01,NaN,NaN,2.645811e+01,NaN,NaN,NaN,NaN
10,Arab World,ARB,Account ownership at a financial institution o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.642109e+01,NaN,NaN,3.523748e+01,NaN,NaN,4.344695e+01,NaN,NaN,NaN,NaN
11,Arab World,ARB,Account ownership at a financial institution o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.070720e+01,NaN,NaN,3.890061e+01,NaN,NaN,4.866698e+01,NaN,NaN,NaN,NaN
12,Arab World,ARB,Account ownership at a financial institution o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.461090e+01,NaN,NaN,2.125614e+01,NaN,NaN,2.095480e+01,NaN,NaN,NaN,NaN
13,Arab World,ARB,Adequacy of social insurance programs (% of to...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Arab World,ARB,Adequacy of social protection and labor progra...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Arab World,ARB,Adequacy of social safety net programs (% of t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Arab World,ARB,Adequacy of unemployment benefits and ALMP (% ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Arab World,ARB,"Adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.504855e+01,7.663139e+01,7.770382e+01,7.898565e+01,8.005233e+01,8.059203e+01,8.111935e+01,8.197276e+01,8.216889e+01,8.303500e+01,8.430093e+01,8.433249e+01,8.543310e+01,8.509152e+01,8.520714e+01,8.421832e+01,8.425430e+01,8.403523e+01,8.453258e+01,8.514375e+01,8.538422e+01,NaN,NaN,NaN
18,Arab World,ARB,"Adjusted net enrollment rate, primary, female ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.028387e+01,7.219401e+01,7.355228e+01,7.517481e+01,7.651463e+01,7.732907e+01,7.794774e+01,7.910946e+01,7.958348e+01,8.044079e+01,8.221837e+01,8.224648e+01,8.355279e+01,8.344254e+01,8.411878e+01,8.321839e+01,8.334494e+01,8.318996e+01,8.382028e+01,8.399478e+01,8.425278e+01,NaN,NaN,NaN
19,Arab World,ARB,"Adjusted net enrollment rate, primary, male (%...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.965690e+01,8.091599e+01,8.171003e+01,8.266111e+01,8.347513e+01,8.375043e+01,8.419786e+01,8.475343e+01,8.469159e+01,8.556248e+01,8.634844e+01,8.638804e+01,8.728571e+01,8.671280e+01,8.630059e+01,8.522583e+01,8.518359e+01,8.489517e+01,8.525464e+01,8.628836e+01,8.650601e+01,NaN,NaN,NaN
20,Arab World,ARB,Adjusted net national income (annual % growth),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.905177e+00,4.635010e+00,8.997872e+00,8.421334e+00,1.215339e+01,7.618434e+00,9.356236e+00,-6.875960e+00,6.809028e+00,1.133159e+01,6.170618e+00,3.037492e+00,1.393947e+00,-6.633045e+00,1.204417e+00,4.783324e+00,3.480929e+00,3.756662e+00,NaN,NaN
21,Arab World,ARB,Adjusted net national income (constant 2010 US$),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.002912e+12,1.042078e+12,1.090378e+12,1.188489e+12,1.288575e+12,1.445181e+12,1.555281e+12,1.700797e+12,1.583851e+12,1.691696e+12,1.883392e+12,1.999609e+12,2.060346e+12,2.089067e+12,1.950498e+12,1.973990e+12,2.068412e+12,2.140412e+12,2.220820e+12,NaN,NaN
22,Arab World,ARB,Adjusted net national income (current US$),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.170882e+11,2.440552e+11,2.522264e+11,2.407152e+11,2.408846e+11,2.397161e+11,2.407680e+11,2.486370e+11,2.515520e+11,2.551702e+11,3.631773e+11,3.587975e+11,3.957672e+11,3.982504e+11,4.011374e+11,4.361064e+11,4.779679e+11,5.114545e+11,5.107796e+11,5.404475e+11,5.872888e+11,5.951391e+11,6.055720e+11,6.677061e+11,7.755357e+11,9.157841e+11,1.100509e+12,1.307867e+12,1.619864e+12,1.461304e+12,1.691696e+12,1.950891e+12,2.190396e+12,2.290530e+12,2.356489e+12,2.147630e+12,2.125136e+12,2.134440e+12,2.294594e+12,2.357838e+12,NaN,NaN
23,Arab World,ARB,Adjusted net national income per capita (annua...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.707281e+00,2.394144e+00,6.608412e+00,5.976271e+00,9.549327e+00,5.064596e+00,6.736940e+00,-9.087875e+00,4.322820e+00,8.796709e+00,3.802541e+00,7.954574e-01,-7.499549e-01,-8.547528e+00,-7.985474e-01,2.780115e+00,1.535596e+00,1.797375e+00,NaN,NaN
24,Arab World,ARB,Adjusted net national income per capita (const...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.477116e+03,3.536480e+03,3.621148e+03,3.860449e+03,4.091160e+03,4.481838e+03,4.708825e+03,5.026056e+03,4.569294e+03,4.766816e+03,5.186139e+03,5.383344e+03,5.426167e+03,5.385473e+03,4.925148e+03,4.885818e+03,5.021650e+03,5.098762e+03,5.190406e+03,NaN,NaN

In [ ]:
#df['indicator_name'].unique().tolist()

I'm considering at this point dropping HELLA countries, because not only do i not wanna deal with this many countiries, but should we? I agree with dealing with more than the ones we menetioned as top, but this? This seems excessive, or I'm being la*y. But deciding which ones to delete would have to be a group thing

Update: we're not gonna drop countries yet. What I am instead going to deal with are all these mf indicators wtf. First thing I will do is make everything lowercase.

In [ ]:
#df['indicator_name'] = df['indicator_name'].str.lower()

In [125]:
df.head(5)

,country_id,ID,indicator_name,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
0,Arab World,ARB,Access to clean fuels and technologies for coo...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.702495,74.944860,76.258066,77.120464,78.094440,79.062000,79.851681,80.570536,81.210886,81.809630,82.368101,82.783289,83.120303,83.533457,83.897596,84.171599,84.510171,NaN,NaN,NaN,NaN,NaN
1,Arab World,ARB,Access to electricity (% of population),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.297851,78.302779,78.980861,78.479364,80.023047,77.999111,79.306311,79.537184,80.574728,84.621206,82.926878,83.644992,84.270921,86.959991,87.199474,87.512260,88.129881,87.275323,88.720097,89.308602,90.283638,89.286856,NaN,NaN,NaN
2,Arab World,ARB,"Access to electricity, rural (% of rural popul...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,54.173305,56.103435,57.350189,57.353298,59.528339,60.383730,62.112010,63.261702,61.626342,64.908930,66.246450,64.850152,64.471295,66.612006,72.367301,68.805997,72.135831,70.506461,75.816160,75.958878,77.251714,78.165706,75.512153,78.211000,79.065508,81.102134,79.248100,NaN,NaN,NaN
3,Arab World,ARB,"Access to electricity, urban (% of urban popul...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.574429,93.022834,93.321986,93.601289,93.556321,95.141707,94.939743,95.712972,95.065438,96.290866,96.466418,96.435957,96.772853,96.466705,96.936319,97.290083,97.467915,97.063959,NaN,NaN,NaN
4,Arab World,ARB,Account ownership at a financial institution o...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.260538,NaN,NaN,30.277130,NaN,NaN,37.165211,NaN,NaN,NaN,NaN

From what i've looked at on excel it will look like it will be 144 indicators per country/area. but we will remove some because some indicators divide into genders. (Look at last review module for removing) We will also want to change the floats to two decimal points.

In [126]:
fuckIt = df

Will be trying a new approach? Also, i'm naming it fuckIt because that was the attitude I had, and it ended up working

In [127]:
df2 = fuckIt[fuckIt.indicator_name == 'Adjusted net enrollment rate, primary (% of primary school age children)']
#df3 = fuckIt[fuckIt.indicator_name == 'Adjusted net enrollment rate, primary, female (% of primary school age children)']
#df4 = fuckIt[fuckIt.indicator_name == 'Adjusted net enrollment rate, primary, male (% of primary school age children)']
df5 = fuckIt[fuckIt.indicator_name == 'Adjusted savings: education expenditure (% of GNI)']
df6 = fuckIt[fuckIt.indicator_name == 'Adjusted savings: education expenditure (current US$)']
df7 = fuckIt[fuckIt.indicator_name == 'Adolescents out of school (% of lower secondary school age)']
#df8 = fuckIt[fuckIt.indicator_name == 'Adolescents out of school, female (% of female lower secondary school age)']
#df9 = fuckIt[fuckIt.indicator_name == 'Adolescents out of school, male (% of male lower secondary school age)']
#df10 = fuckIt[fuckIt.indicator_name == 'Average working hours of children, study and work, ages 7-14 (hours per week)']
#df11 = fuckIt[fuckIt.indicator_name == 'Average working hours of children, study and work, female, ages 7-14 (hours per week)']
#df12 = fuckIt[fuckIt.indicator_name == 'Average working hours of children, study and work, male, ages 7-14 (hours per week)']
df13 = fuckIt[fuckIt.indicator_name == 'Children out of school (% of primary school age)']
#df14 = fuckIt[fuckIt.indicator_name == 'Children out of school, female (% of female primary school age)']
#df15 = fuckIt[fuckIt.indicator_name == 'Children out of school, male (% of male primary school age)']
df16 = fuckIt[fuckIt.indicator_name == 'Children out of school, primary']
#df17 = fuckIt[fuckIt.indicator_name == 'Children out of school, primary, female']
#df18 = fuckIt[fuckIt.indicator_name == 'Children out of school, primary, male']
df19 = fuckIt[fuckIt.indicator_name == 'Compulsory education, duration (years)']
df20 = fuckIt[fuckIt.indicator_name == 'Current education expenditure, primary (% of total expenditure in primary public institutions)']
df21 = fuckIt[fuckIt.indicator_name == 'Current education expenditure, secondary (% of total expenditure in secondary public institutions)']
df22 = fuckIt[fuckIt.indicator_name == 'Current education expenditure, tertiary (% of total expenditure in tertiary public institutions)']
df23 = fuckIt[fuckIt.indicator_name == 'Current education expenditure, total (% of total expenditure in public institutions)']
#df24 = fuckIt[fuckIt.indicator_name == "Educational attainment, at least Bachelor's or equivalent, population 25+, female (%) (cumulative)"]
#df25 = fuckIt[fuckIt.indicator_name == "Educational attainment, at least Bachelor's or equivalent, population 25+, male (%) (cumulative)"]
#df26 = fuckIt[fuckIt.indicator_name == "Educational attainment, at least Bachelor's or equivalent, population 25+, total (%) (cumulative)"]
df27 = fuckIt[fuckIt.indicator_name == 'Educational attainment, at least completed lower secondary, population 25+, female (%) (cumulative)']
df28 = fuckIt[fuckIt.indicator_name == 'Educational attainment, at least completed lower secondary, population 25+, male (%) (cumulative)']
df29 = fuckIt[fuckIt.indicator_name == 'Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)']
df30 = fuckIt[fuckIt.indicator_name == 'Educational attainment, at least completed post-secondary, population 25+, female (%) (cumulative)']
df31 = fuckIt[fuckIt.indicator_name == 'Educational attainment, at least completed post-secondary, population 25+, male (%) (cumulative)']
df32 = fuckIt[fuckIt.indicator_name == 'Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative)']
df33 = fuckIt[fuckIt.indicator_name == 'Educational attainment, at least completed primary, population 25+ years, female (%) (cumulative)']
df34 = fuckIt[fuckIt.indicator_name == 'Educational attainment, at least completed primary, population 25+ years, male (%) (cumulative)']
df35 = fuckIt[fuckIt.indicator_name == 'Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative)']
#df36 = fuckIt[fuckIt.indicator_name == 'Educational attainment, at least completed short-cycle tertiary, population 25+, female (%) (cumulative)']
#df37 = fuckIt[fuckIt.indicator_name == 'Educational attainment, at least completed short-cycle tertiary, population 25+, male (%) (cumulative)']
#df38 = fuckIt[fuckIt.indicator_name == 'Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative)']
df39 = fuckIt[fuckIt.indicator_name == 'Educational attainment, at least completed upper secondary, population 25+, female (%) (cumulative)']
df40 = fuckIt[fuckIt.indicator_name == 'Educational attainment, at least completed upper secondary, population 25+, male (%) (cumulative)']
df41 = fuckIt[fuckIt.indicator_name == 'Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative)']
#df42 = fuckIt[fuckIt.indicator_name == "Educational attainment, at least Master's or equivalent, population 25+, female (%) (cumulative)"]
#df43 = fuckIt[fuckIt.indicator_name == "Educational attainment, at least Master's or equivalent, population 25+, male (%) (cumulative)"]
#df44 = fuckIt[fuckIt.indicator_name == "Educational attainment, at least Master's or equivalent, population 25+, total (%) (cumulative)"]
#df45 = fuckIt[fuckIt.indicator_name == 'Educational attainment, Doctoral or equivalent, population 25+, female (%) (cumulative)']
#df46 = fuckIt[fuckIt.indicator_name == 'Educational attainment, Doctoral or equivalent, population 25+, male (%) (cumulative)']
#df47 = fuckIt[fuckIt.indicator_name == 'Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative)']
df48 = fuckIt[fuckIt.indicator_name == 'Expenditure on primary education (% of government expenditure on education)']
df49 = fuckIt[fuckIt.indicator_name == 'Expenditure on secondary education (% of government expenditure on education)']
#df50 = fuckIt[fuckIt.indicator_name == 'Expenditure on tertiary education (% of government expenditure on education)']
df51 = fuckIt[fuckIt.indicator_name == 'GDP growth (annual %)']
df52 = fuckIt[fuckIt.indicator_name == 'Government expenditure on education, total (% of GDP)']
df53 = fuckIt[fuckIt.indicator_name == 'Government expenditure on education, total (% of government expenditure)']
df54 = fuckIt[fuckIt.indicator_name == 'Government expenditure per student, primary (% of GDP per capita)']
df55 = fuckIt[fuckIt.indicator_name == 'Government expenditure per student, secondary (% of GDP per capita)']
#df56 = fuckIt[fuckIt.indicator_name == 'Government expenditure per student, tertiary (% of GDP per capita)']
#df57 = fuckIt[fuckIt.indicator_name == 'Gross intake ratio in first grade of primary education, female (% of relevant age group)']
#df58 = fuckIt[fuckIt.indicator_name == 'Gross intake ratio in first grade of primary education, male (% of relevant age group)']
df59 = fuckIt[fuckIt.indicator_name == 'Gross intake ratio in first grade of primary education, total (% of relevant age group)']
#df60 = fuckIt[fuckIt.indicator_name == 'Individuals using the Internet (% of population)']
#df61 = fuckIt[fuckIt.indicator_name == 'Literacy rate, adult female (% of females ages 15 and above)']
#df62 = fuckIt[fuckIt.indicator_name == 'Literacy rate, adult male (% of males ages 15 and above)']
#df63 = fuckIt[fuckIt.indicator_name == 'Literacy rate, adult total (% of people ages 15 and above)']
#df64 = fuckIt[fuckIt.indicator_name == 'Literacy rate, youth (ages 15-24), gender parity index (GPI)']
#df65 = fuckIt[fuckIt.indicator_name == 'Literacy rate, youth female (% of females ages 15-24)']
#df66 = fuckIt[fuckIt.indicator_name == 'Literacy rate, youth male (% of males ages 15-24)']
df67 = fuckIt[fuckIt.indicator_name == 'Literacy rate, youth total (% of people ages 15-24)']
#df68 = fuckIt[fuckIt.indicator_name == 'Net intake rate in grade 1 (% of official school-age population)']
#df69 = fuckIt[fuckIt.indicator_name == 'Net intake rate in grade 1, female (% of official school-age population)']
#df70 = fuckIt[fuckIt.indicator_name == 'Net intake rate in grade 1, male (% of official school-age population)']
#df71 = fuckIt[fuckIt.indicator_name == 'Over-age students, primary (% of enrollment)']
#df72 = fuckIt[fuckIt.indicator_name == 'Over-age students, primary, female (% of female enrollment)']
#df73 = fuckIt[fuckIt.indicator_name == 'Over-age students, primary, male (% of male enrollment)']
#df74 = fuckIt[fuckIt.indicator_name == 'Population ages 0-14 (% of total population)']
#df75 = fuckIt[fuckIt.indicator_name == 'Population ages 0-14, female (% of female population)']
#df76 = fuckIt[fuckIt.indicator_name == 'Population ages 0-14, male (% of male population)']
#df77 = fuckIt[fuckIt.indicator_name == 'Population ages 0-14, total']
#df78 = fuckIt[fuckIt.indicator_name == 'Population ages 15-19, female (% of female population)']
#df79 = fuckIt[fuckIt.indicator_name == 'Population ages 15-19, male (% of male population)']
df80 = fuckIt[fuckIt.indicator_name == 'Preprimary education, duration (years)']
#df81 = fuckIt[fuckIt.indicator_name == 'Primary completion rate, female (% of relevant age group)']
#df82 = fuckIt[fuckIt.indicator_name == 'Primary completion rate, male (% of relevant age group)']
df83 = fuckIt[fuckIt.indicator_name == 'Primary completion rate, total (% of relevant age group)']
df84 = fuckIt[fuckIt.indicator_name == 'Primary education, duration (years)']
df85 = fuckIt[fuckIt.indicator_name == 'Primary education, pupils']
df86 = fuckIt[fuckIt.indicator_name == 'Primary education, pupils (% female)']
df87 = fuckIt[fuckIt.indicator_name == 'Primary education, teachers']
df88 = fuckIt[fuckIt.indicator_name == 'Primary education, teachers (% female)']
df89 = fuckIt[fuckIt.indicator_name == 'Primary school starting age (years)']
df90 = fuckIt[fuckIt.indicator_name == 'Pupil-teacher ratio, lower secondary']
df91 = fuckIt[fuckIt.indicator_name == 'Pupil-teacher ratio, preprimary']
df92 = fuckIt[fuckIt.indicator_name == 'Pupil-teacher ratio, primary']
df93 = fuckIt[fuckIt.indicator_name == 'Pupil-teacher ratio, secondary']
#df94 = fuckIt[fuckIt.indicator_name == 'Pupil-teacher ratio, tertiary']
df95 = fuckIt[fuckIt.indicator_name == 'Pupil-teacher ratio, upper secondary']
df96 = fuckIt[fuckIt.indicator_name == 'School enrollment, preprimary (% gross)']
#df97 = fuckIt[fuckIt.indicator_name == 'School enrollment, preprimary, female (% gross)']
#df98 = fuckIt[fuckIt.indicator_name == 'School enrollment, preprimary, male (% gross)']
df99 = fuckIt[fuckIt.indicator_name == 'School enrollment, primary (% gross)']
#df100 = fuckIt[fuckIt.indicator_name == 'School enrollment, primary (% net)']
df101 = fuckIt[fuckIt.indicator_name == 'School enrollment, primary (gross), gender parity index (GPI)']
df102 = fuckIt[fuckIt.indicator_name == 'School enrollment, primary and secondary (gross), gender parity index (GPI)']
#df103 = fuckIt[fuckIt.indicator_name == 'School enrollment, primary, female (% gross)']
#df104 = fuckIt[fuckIt.indicator_name == 'School enrollment, primary, female (% net)']
#df105 = fuckIt[fuckIt.indicator_name == 'School enrollment, primary, male (% gross)']
#df106 = fuckIt[fuckIt.indicator_name == 'School enrollment, primary, male (% net)']
#df107 = fuckIt[fuckIt.indicator_name == 'School enrollment, primary, private (% of total primary)']
df108 = fuckIt[fuckIt.indicator_name == 'School enrollment, secondary (% gross)']
#df109 = fuckIt[fuckIt.indicator_name == 'School enrollment, secondary (% net)']
df110 = fuckIt[fuckIt.indicator_name == 'School enrollment, secondary (gross), gender parity index (GPI)']
#df111 = fuckIt[fuckIt.indicator_name == 'School enrollment, secondary, female (% gross)']
#df112 = fuckIt[fuckIt.indicator_name == 'School enrollment, secondary, female (% net)']
#df113 = fuckIt[fuckIt.indicator_name == 'School enrollment, secondary, male (% gross)']
#df114 = fuckIt[fuckIt.indicator_name == 'School enrollment, secondary, male (% net)']
#df115 = fuckIt[fuckIt.indicator_name == 'School enrollment, secondary, private (% of total secondary)']
#df116 = fuckIt[fuckIt.indicator_name == 'School enrollment, tertiary (% gross)']
#df117 = fuckIt[fuckIt.indicator_name == 'School enrollment, tertiary (gross), gender parity index (GPI)']
#df118 = fuckIt[fuckIt.indicator_name == 'School enrollment, tertiary, female (% gross)']
#df119 = fuckIt[fuckIt.indicator_name == 'School enrollment, tertiary, male (% gross)']
df120 = fuckIt[fuckIt.indicator_name == 'Secondary education, duration (years)']
#df121 = fuckIt[fuckIt.indicator_name == 'Secondary education, general pupils']
#df122 = fuckIt[fuckIt.indicator_name == 'Secondary education, general pupils (% female)']
#df123 = fuckIt[fuckIt.indicator_name == 'Secondary education, pupils']
#df124 = fuckIt[fuckIt.indicator_name == 'Secondary education, pupils (% female)']
#df125 = fuckIt[fuckIt.indicator_name == 'Secondary education, teachers']
#df126 = fuckIt[fuckIt.indicator_name == 'Secondary education, teachers (% female)']
#df127 = fuckIt[fuckIt.indicator_name == 'Secondary education, teachers, female']
#df128 = fuckIt[fuckIt.indicator_name == 'Secondary education, vocational pupils']
#df129 = fuckIt[fuckIt.indicator_name == 'Secondary education, vocational pupils (% female)']
#df130 = fuckIt[fuckIt.indicator_name == 'Tertiary education, academic staff (% female)']
df131 = fuckIt[fuckIt.indicator_name == 'Trained teachers in lower secondary education (% of total teachers)']
#df132 = fuckIt[fuckIt.indicator_name == 'Trained teachers in lower secondary education, female (% of female teachers)']
#df133 = fuckIt[fuckIt.indicator_name == 'Trained teachers in lower secondary education, male (% of male teachers)']
df134 = fuckIt[fuckIt.indicator_name == 'Trained teachers in preprimary education (% of total teachers)']
#df135 = fuckIt[fuckIt.indicator_name == 'Trained teachers in preprimary education, female (% of female teachers)']
#df136 = fuckIt[fuckIt.indicator_name == 'Trained teachers in preprimary education, male (% of male teachers)']
df137 = fuckIt[fuckIt.indicator_name == 'Trained teachers in primary education (% of total teachers)']
#df138 = fuckIt[fuckIt.indicator_name == 'Trained teachers in primary education, female (% of female teachers)']
#df139 = fuckIt[fuckIt.indicator_name == 'Trained teachers in primary education, male (% of male teachers)']
df140 = fuckIt[fuckIt.indicator_name == 'Trained teachers in secondary education (% of total teachers)']
#df141 = fuckIt[fuckIt.indicator_name == 'Trained teachers in secondary education, female (% of female teachers)']
#df142 = fuckIt[fuckIt.indicator_name == 'Trained teachers in secondary education, male (% of male teachers)']
df143 = fuckIt[fuckIt.indicator_name == 'Trained teachers in upper secondary education (% of total teachers)']
#df144 = fuckIt[fuckIt.indicator_name == 'Trained teachers in upper secondary education, female (% of female teachers)']
#df145 = fuckIt[fuckIt.indicator_name == 'Trained teachers in upper secondary education, male (% of male teachers)']

In [128]:
world_data_drivers = df2.append([df5,df6,df7,df13,df16,df19,df20,
    df21,df22,df23,df27,df28,df29,df30,df31,df32,df33,df34,df35,
    df39,df40,df41,df48,df49,df51,df52,df53,df54,df55,df59,df67,
    df80,df83,df84,df85,df86,df87,df88,df89,df90,df91,df92,df93,
    df95,df96,df99,df101,df102,df108,df110,df120,df131,df134,
    df137,df140,df143])

In [129]:
world_data_drivers.head(120)

,country_id,ID,indicator_name,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
17,Arab World,ARB,"Adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.04855,76.63139,77.70382,78.98565,80.05233,80.59203,81.11935,81.97276,82.16889,83.03500,84.30093,84.33249,85.43310,85.09152,85.20714,84.21832,84.25430,84.03523,84.53258,85.14375,85.38422,NaN,NaN,NaN
1460,Caribbean small states,CSS,"Adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.33843,92.56256,91.89613,90.42253,90.22634,91.60736,91.09519,90.70505,90.85378,91.16740,90.41794,90.64584,90.87925,90.46721,89.77977,89.57198,90.92441,90.48512,89.39624,88.92917,NaN,NaN,NaN
2903,Central Europe and the Baltics,CEB,"Adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.53525,93.83107,94.37633,93.31489,93.88601,93.71377,93.50322,93.23661,93.03312,93.02446,94.38691,94.42270,94.53438,94.75666,94.59641,94.65734,94.01037,93.41415,93.45411,93.06906,92.81936,91.02484,NaN,NaN,NaN
4346,Early-demographic dividend,EAR,"Adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.29524,91.65029,91.50120,92.00800,92.59810,92.79595,92.64547,92.86882,92.95517,92.98126,NaN,NaN,NaN
5789,East Asia & Pacific,EAS,"Adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.70754,NaN,NaN,95.99079,96.06234,95.98306,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165962,France,FRA,"Adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.34870,97.27084,97.31155,97.57172,NaN,96.81501,96.94516,NaN,98.94168,99.29482,98.85366,97.61584,95.46911,NaN,94.87775,97.61482,99.88708,99.84556,99.85966,99.91749,99.98827,99.21937,97.83304,97.79167,98.94106,99.94659,99.93910,NaN,96.57289,96.18632,96.09347,96.04528,95.82227,95.78781,99.23101,99.26235,99.18236,98.74538,98.38524,98.01978,99.03727,98.91622,98.91152,98.15483,98.99877,99.37467,99.46800,NaN,NaN,NaN,NaN
167405,French Polynesia,PYF,"Adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.84164,94.59014,93.30883,NaN,NaN,NaN,98.65302,99.62628,NaN,NaN,99.34081,NaN,99.58108,99.38568,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168848,Gabon,GAB,"Adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.32442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.90869,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170291,"Gambia, The",GMB,"Adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.92524,20.81935,22.07092,22.54759,23.69834,25.22417,29.18221,31.7409,35.70421,40.40406,48.89858,52.95195,56.37778,58.14528,60.93532,60.64459,NaN,NaN,NaN,49.01772,NaN,47.82232,51.04922,NaN,NaN,58.23200,NaN,58.89308,67.98373,64.52230,64.28849,62.12240,65.33112,65.77435,63.87335,68.63829,70.67140,66.64450,NaN,67.89345,67.30464,70.27827,70.03975,69.82179,75.91325,77.65176,80.15436,81.80852,NaN,NaN,NaN
171734,Georgia,GEO,"Adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.41798,98.29222,99.86955,NaN,NaN,NaN,NaN,NaN,NaN,94.62166,93.91598,92.87640,99.34911,98.59770,96.92210,NaN,97.59425,98.77982,99.55879,99.31588,99.73715,97.95282,99.24104,99.21379,NaN,NaN,NaN

In [130]:
world_data_drivers['indicator_name'] = world_data_drivers['indicator_name'].str.lower()

In [132]:
world_data_drivers.head(5)

,country_id,ID,indicator_name,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
17,Arab World,ARB,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.04855,76.63139,77.70382,78.98565,80.05233,80.59203,81.11935,81.97276,82.16889,83.03500,84.30093,84.33249,85.43310,85.09152,85.20714,84.21832,84.25430,84.03523,84.53258,85.14375,85.38422,NaN,NaN,NaN
1460,Caribbean small states,CSS,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.33843,92.56256,91.89613,90.42253,90.22634,91.60736,91.09519,90.70505,90.85378,91.16740,90.41794,90.64584,90.87925,90.46721,89.77977,89.57198,90.92441,90.48512,89.39624,88.92917,NaN,NaN,NaN
2903,Central Europe and the Baltics,CEB,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.53525,93.83107,94.37633,93.31489,93.88601,93.71377,93.50322,93.23661,93.03312,93.02446,94.38691,94.42270,94.53438,94.75666,94.59641,94.65734,94.01037,93.41415,93.45411,93.06906,92.81936,91.02484,NaN,NaN,NaN
4346,Early-demographic dividend,EAR,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.29524,91.65029,91.50120,92.00800,92.59810,92.79595,92.64547,92.86882,92.95517,92.98126,NaN,NaN,NaN
5789,East Asia & Pacific,EAS,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.70754,NaN,NaN,95.99079,96.06234,95.98306,NaN,NaN,NaN

In [133]:
world_data_drivers.shape

(15048, 65)

In [134]:
world_data_drivers.round(decimals= 2)

,country_id,ID,indicator_name,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
17,Arab World,ARB,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.05,76.63,77.70,78.99,80.05,80.59,81.12,81.97,82.17,83.04,84.30,84.33,85.43,85.09,85.21,84.22,84.25,84.04,84.53,85.14,85.38,NaN,NaN,NaN
1460,Caribbean small states,CSS,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,92.34,92.56,91.90,90.42,90.23,91.61,91.10,90.71,90.85,91.17,90.42,90.65,90.88,90.47,89.78,89.57,90.92,90.49,89.40,88.93,NaN,NaN,NaN
2903,Central Europe and the Baltics,CEB,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.54,93.83,94.38,93.31,93.89,93.71,93.50,93.24,93.03,93.02,94.39,94.42,94.53,94.76,94.60,94.66,94.01,93.41,93.45,93.07,92.82,91.02,NaN,NaN,NaN
4346,Early-demographic dividend,EAR,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91.30,91.65,91.50,92.01,92.60,92.80,92.65,92.87,92.96,92.98,NaN,NaN,NaN
5789,East Asia & Pacific,EAS,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.71,NaN,NaN,95.99,96.06,95.98,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375111,Virgin Islands (U.S.),VIR,trained teachers in upper secondary education ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
376554,West Bank and Gaza,PSE,trained teachers in upper secondary education ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.00,100.00,100.00,100.00,NaN,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.0,NaN,NaN
377997,"Yemen, Rep.",YEM,trained teachers in upper secondary education ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
379440,Zambia,ZMB,trained teachers in upper secondary education ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
380883,Zimbabwe,ZWE,trained teachers in upper secondary education ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [135]:
world_data_drivers.dtypes

country_id        category
ID                category
indicator_name      object
1960               float64
1961               float64
                    ...
2017               float64
2018               float64
2019               float64
2020               float64
Unnamed: 65        float64
Length: 65, dtype: object

In [ ]:
for i in world_data_drivers:
    print(world_data_drivers[i].isnull().sum())

Because of the above finding, I feel instead as though I should eliminate rows on my own, or maybe I should just make sure there are countries instead of regions.

In [ ]:
world_data_drivers['country_id'].unique().tolist()

In [136]:
get_rid_country = ["Arab World", "Caribbean small states", "Central Europe and the Baltics", "Early-demographic dividend", "East Asia & Pacific",
    "East Asia & Pacific (excluding high income)", "East Asia & Pacific (IDA & IBRD countries)", "Euro area", "Europe & Central Asia",
     "Europe & Central Asia (excluding high income)","Europe & Central Asia (IDA & IBRD countries)", "European Union", "Fragile and conflict affected situations",
      "Heavily indebted poor countries (HIPC)", "High income", "IBRD only", "IDA & IBRD total", "IDA blend", "IDA only", "IDA total", "Late-demographic dividend",
       "Latin America & Caribbean", "Latin America & Caribbean (excluding high income)", "Latin America & the Caribbean (IDA & IBRD countries)",
        "Least developed countries: UN classification", "Low & middle income", "Low income", "Lower middle income", "Middle East & North Africa",
         "Middle East & North Africa (excluding high income)", "Middle East & North Africa (IDA & IBRD countries)", "Middle income", "North America",
          "Not classified", "OECD members", "Other small states", "Pacific island small states", "Post-demographic dividend", "Pre-demographic dividend",
           "Small states", "South Asia", "South Asia (IDA & IBRD)", "Sub-Saharan Africa", "Sub-Saharan Africa (excluding high income)",
            "Sub-Saharan Africa (IDA & IBRD countries)", "Upper middle income", "World"]

In [137]:
test_elim = world_data_drivers #creating a new data set to test get ridding of all these sub-cats of countries

In [138]:
test_elim = test_elim[~test_elim['country_id'].isin(get_rid_country)]

In [139]:
test_elim.shape

(12369, 65)

In [141]:
test_elim.head(10)

,country_id,ID,indicator_name,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
67838,Afghanistan,AFG,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.82221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.76600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69281,Albania,ALB,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.79354,95.38335,93.86551,NaN,91.69871,90.92345,NaN,NaN,NaN,86.78701,85.34118,85.95611,86.99052,89.53195,95.41897,97.59204,97.79873,97.65542,97.77841,97.44221,NaN,NaN,NaN
70724,Algeria,DZA,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.87061,71.78052,74.18978,76.1599,77.72608,78.77859,78.87035,79.98721,80.25392,79.92768,79.26301,80.29434,80.65069,81.81824,83.14107,84.25691,85.33525,85.87007,87.60795,88.70739,88.22298,88.16877,88.39232,87.9189,87.36391,NaN,90.05305,90.74774,92.74897,93.90213,94.35822,95.08431,95.39817,95.64397,95.89073,97.26895,98.99715,98.92068,99.08721,NaN,NaN,NaN,NaN,NaN,99.48537,99.64750,NaN,NaN,NaN
72167,American Samoa,ASM,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73610,Andorra,AND,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75053,Angola,AGO,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.19862,42.53922,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.34669,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.44691,81.25930,81.90919,81.59927,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76496,Antigua and Barbuda,ATG,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,97.35554,97.58825,NaN,96.32810,95.97518,94.87391,NaN,93.73436,97.63492,NaN,97.55055,99.31010,NaN,NaN,NaN
77939,Argentina,ARG,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.12735,NaN,NaN,NaN,96.62253,96.32775,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.45755,NaN,NaN,NaN,96.17590,NaN,NaN,NaN,NaN,NaN,100.00000,99.73430,99.62729,99.35688,99.43632,99.45558,99.42561,99.13676,99.34854,99.52115,99.65259,99.52275,99.51247,99.13102,99.21521,99.26778,99.44548,99.77270,99.83682,99.44960,99.48052,NaN,NaN,NaN,NaN
79382,Armenia,ARM,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.13120,85.53043,NaN,88.61333,92.21765,97.07957,NaN,NaN,NaN,95.15386,96.41176,96.58810,94.12688,93.03258,92.49744,92.31421,90.84300,NaN,NaN,NaN
80825,Aruba,ABW,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98.01382,98.24184,96.62665,95.40839,93.97484,94.77636,97.97892,98.66020,98.91579,99.10333,96.01740,98.91975,NaN,NaN,NaN,99.29199,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
for i in test_elim:
    print(test_elim[i].isnull().sum())

I think it might be that there a lot of countries that do not participate in providing the data maybe. Will see once we save this shit.

In [143]:
world_data_final = test_elim.round(decimals= 2)

In [145]:
world_data_final = world_data_final.reset_index(drop = True)

In [146]:
world_data_final

,country_id,ID,indicator_name,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
0,Afghanistan,AFG,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Albania,ALB,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,96.79,95.38,93.87,NaN,91.70,90.92,NaN,NaN,NaN,86.79,85.34,85.96,86.99,89.53,95.42,97.59,97.8,97.66,97.78,97.44,NaN,NaN,NaN
2,Algeria,DZA,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,67.87,71.78,74.19,76.16,77.73,78.78,78.87,79.99,80.25,79.93,79.26,80.29,80.65,81.82,83.14,84.26,85.34,85.87,87.61,88.71,88.22,88.17,88.39,87.92,87.36,NaN,90.05,90.75,92.75,93.9,94.36,95.08,95.4,95.64,95.89,97.27,99.00,98.92,99.09,NaN,NaN,NaN,NaN,NaN,99.49,99.65,NaN,NaN,NaN
3,American Samoa,ASM,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andorra,AND,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12364,Virgin Islands (U.S.),VIR,trained teachers in upper secondary education ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12365,West Bank and Gaza,PSE,trained teachers in upper secondary education ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.0,100.00,100.00,100.0,NaN,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.0,100.00,100.00,100.00,100.0,NaN,NaN
12366,"Yemen, Rep.",YEM,trained teachers in upper secondary education ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,94.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12367,Zambia,ZMB,trained teachers in upper secondary education ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12368,Zimbabwe,ZWE,trained teachers in upper secondary education ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [147]:
world_data_final = world_data_final.drop(columns=['Unnamed: 65']) #2020 you're next

In [ ]:
world_data_final.shape

After looking at the data in an excel sheet, I see that we don't really need the years 1960-1969. The only available data for those columns are the indicators pertaining to the population at that time, which are not going to be strong indicators in my opinion.

In [148]:
years_to_get_rid = ['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967',
    '1968', '1969','1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
    '1978', '1979','1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987',
    '1988', '1989','1990', '1991', '1992', '1993', '1994']

In [149]:
#world_data_final = world_data_final.drop(columns = ['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969']) ##2020 you're still next

world_data_final = world_data_final.drop( columns = years_to_get_rid)

In [150]:
pd.options.display.max_columns = 100
world_data_final.head(5)

,country_id,ID,indicator_name,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Afghanistan,AFG,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Albania,ALB,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,96.79,95.38,93.87,NaN,91.70,90.92,NaN,NaN,NaN,86.79,85.34,85.96,86.99,89.53,95.42,97.59,97.8,97.66,97.78,97.44,NaN,NaN
2,Algeria,DZA,"adjusted net enrollment rate, primary (% of pr...",88.39,87.92,87.36,NaN,90.05,90.75,92.75,93.9,94.36,95.08,95.4,95.64,95.89,97.27,99.00,98.92,99.09,NaN,NaN,NaN,NaN,NaN,99.49,99.65,NaN,NaN
3,American Samoa,ASM,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andorra,AND,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [151]:
list_of_countries = [world_data_final['country_id'].unique()]

What I can do is create a multi-index dataframe and then find the missing values by each country there? Since there will only be one element in `country_name` of the country.

Trying to make an argument to deleting  a bunch of countries too. Many countries do not measure PISA scores, so I feel like what is the need to have them here, if thye do not have data for what we want. I am using a different data set, from the world data bank for this to determine which countries do not have PISA data.

In [152]:
countries_no_pisa = ['Afghanistan', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Armenia', 'Aruba', 'Bahamas, The',
     'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 
     'British Virgin Islands', 'Brunei Darussalam', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Cayman Islands', 'Chad',
     'Channel Islands', 'Comoros', 'Congo, Dem. Rep.', 'Congo, Rep.', "Cote d'Ivoire", 'Cuba', 'Curacao', 'Djibouti', 'Dominica', 'Ecuador',
     'Egypt, Arab Rep.', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Ethiopia', 'Faroe Islands', 'Fiji', 'French Polynesia',
     'Gabon', 'Gambia, The', 'Ghana', 'Gibraltar', 'Greenland', 'Grenada', 'Guam', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
     'Honduras', 'India', 'Iran, Islamic Rep.', 'Iraq', 'Isle of Man', 'Jamaica', 'Kenya', 'Kiribati', 'Korea, Dem. People’s Rep.', 'Kuwait',
     'Lao PDR', 'Lesotho', 'Liberia', 'Libya', 'Madagascar', 'Malawi', 'Maldives', 'Mali', 'Marshall Islands', 'Mauritania', 'Mauritius', 
     'Mayotte', 'Micronesia, Fed. Sts.', 'Moldova', 'Monaco', 'Mongolia', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal',
     'Netherlands Antilles', 'New Caledonia', 'Nicaragua', 'Niger', 'Nigeria', 'Northern Mariana Islands', 'Oman', 'Pakistan', 'Palau', 'Papua New Guinea', 
     'Paraguay', 'Philippines', 'Puerto Rico', 'Rwanda', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Seychelles',
     'Sierra Leone', 'Sint Maarten (Dutch part)', 'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan', 'Sri Lanka', 'St. Kitts and Nevis', 
     'St. Lucia', 'St. Martin (French part)', 'St. Vincent and the Grenadines', 'Sudan', 'Suriname', 'Syrian Arab Republic', 'Tajikistan', 'Tanzania',
     'Timor-Leste', 'Togo', 'Tokelau', 'Tonga', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'Uzbekistan', 'Vanuatu',
     'Venezuela, RB', 'Virgin Islands (U.S.)', 'West Bank and Gaza', 'Yemen, Rep.', 'Zambia', 'Zimbabwe']

In [153]:
test_elim2 = world_data_final

In [154]:
test_elim2 = test_elim2[~test_elim2['country_id'].isin(countries_no_pisa)]

In [ ]:
test_elim2.head(50)

In [ ]:
for i in test_elim2:
    print(test_elim2[i].isnull().sum())

That's honestly a lot better in my opinion, if someone thinks otherwise, it's on sight.

In [158]:
final_code = test_elim2

In [159]:
final_code.head(15)

,country_id,ID,indicator_name,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
1,Albania,ALB,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,96.79,95.38,93.87,NaN,91.70,90.92,NaN,NaN,NaN,86.79,85.34,85.96,86.99,89.53,95.42,97.59,97.80,97.66,97.78,97.44,NaN,NaN
7,Argentina,ARG,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,100.00,99.73,99.63,99.36,99.44,99.46,99.43,99.14,99.35,99.52,99.65,99.52,99.51,99.13,99.22,99.27,99.45,99.77,99.84,99.45,99.48,NaN,NaN,NaN
10,Australia,AUS,"adjusted net enrollment rate, primary (% of pr...",95.00,95.40,94.98,94.92,94.55,94.49,93.96,94.03,95.02,95.38,95.68,95.78,96.55,96.68,96.81,97.10,97.68,97.99,97.48,97.14,97.11,96.77,96.50,NaN,NaN,NaN
11,Austria,AUT,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,90.24,91.25,90.31,88.37,87.47,87.70,87.84,88.25,88.20,87.79,87.47,87.39,87.19,88.43,88.42,88.74,88.63,88.88,88.64,NaN,NaN,NaN
12,Azerbaijan,AZE,"adjusted net enrollment rate, primary (% of pr...",84.66,93.51,90.13,88.73,92.14,88.24,85.46,84.91,83.35,84.28,83.95,83.77,83.46,83.99,85.52,84.73,87.27,89.29,93.67,94.81,94.26,94.97,97.93,92.62,NaN,NaN
18,Belgium,BEL,"adjusted net enrollment rate, primary (% of pr...",97.08,97.54,NaN,NaN,99.13,99.19,99.18,98.95,97.97,96.36,95.99,96.31,97.25,97.84,97.77,97.53,97.65,97.99,98.03,97.97,98.38,98.66,99.11,NaN,NaN,NaN
26,Brazil,BRA,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,98.07,NaN,98.85,96.73,94.30,95.59,96.08,NaN,92.47,98.54,96.59,NaN,95.70,98.55,97.32,97.44,96.85,97.20,97.55,NaN,NaN,NaN
29,Bulgaria,BGR,"adjusted net enrollment rate, primary (% of pr...",NaN,93.94,95.00,97.46,97.58,97.09,97.11,96.03,96.28,96.96,95.79,96.77,99.52,99.67,99.30,99.51,99.50,97.19,95.34,94.01,91.99,89.46,88.09,NaN,NaN,NaN
35,Canada,CAN,"adjusted net enrollment rate, primary (% of pr...",94.76,95.69,NaN,99.15,99.93,99.92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.45,99.43,99.39,99.59,99.96,NaN,NaN,NaN,NaN
37,Central African Republic,CAF,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.62,47.84,55.58,64.14,64.27,NaN,64.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Chile,CHL,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,95.55,96.10,94.52,95.48,94.82,94.54,93.69,93.46,93.47,94.04,94.78,NaN,NaN,NaN
41,China,CHN,"adjusted net enrollment rate, primary (% of pr...",91.30,90.04,89.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Colombia,COL,"adjusted net enrollment rate, primary (% of pr...",84.47,89.28,NaN,95.15,96.34,96.77,94.85,95.92,NaN,94.56,97.37,96.31,95.71,NaN,NaN,NaN,NaN,95.24,92.80,92.91,96.38,95.42,97.35,97.76,NaN,NaN
46,Costa Rica,CRI,"adjusted net enrollment rate, primary (% of pr...",89.54,91.47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99.43,99.47,98.90,97.22,97.82,98.37,96.55,97.41,NaN,NaN
48,Croatia,HRV,"adjusted net enrollment rate, primary (% of pr...",NaN,NaN,NaN,84.00,92.58,93.91,96.17,98.28,99.73,NaN,98.94,98.93,98.87,97.20,91.50,94.76,96.97,98.58,98.27,98.40,98.49,97.85,97.99,NaN,NaN,NaN

In [ ]:
 ###Creating a multi index dataframe using country as the main main.
maybe_better = final_code.pivot_table(index = ['country_id','country_code','indicator_name'])

In [ ]:
maybe_better.head(5)

In [160]:
final_code.to_csv("/Users/josejimenez/Downloads/world_data_bank_clean2.csv", encoding = "utf-8", index = False)